// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Enum CourseLevel {
  EASY
  MEDIUM
  DIFICULT
}

Enum UserRole {
  ADMIN
  INSTRUCTOR
  STUDENT
}

Table User {
  id integer [primary key]
  first_name varchar
  last_name varchar
  username varchar
  bio text
  email varchar
  password varchar
  phoneno number
  image_url varchar
  image_id varchar
  role UserRole  
  courses_enrolled_ids integer[]  [ref: > Course.id] 
  modules_completed_ids integer[] [ref: > Module.id] 
  otp integer
  otp_status varchar
  otp_expiration_date timestamp
  reset_token varchar
  reset_token_expiration_date timestamp
  created_at timestamp
  updated_at timestamp
}

Table Instructor {
  id integer [primary key]
  courses_taught_ids integer[] [ref: > Course.id] 
  user_id integer
  created_at timestamp
  updated_at timestamp
}

Table Course {
  id integer [primary key]
  title varchar
  content_type varchar
  description text [note: 'about the course']
  instructor_id integer 
  category_id integer [ref: > Category.id]
  level CourseLevel
  price integer
  enrollment_key varchar
  start_date timestamp
  end_date timestamp
  duration varchar 
  module_ids integer[]
  students_enrolled_ids integer[] [ref: > User.id]
  created_at timestamp
  updated_at timestamp
}

Table Category {
  id integer [primary key]
  name varchar
  description text
  courses integer[] [ref: > Course.id]
}

Table CourseCategory {
  course_id integer [ref: > Course.id]
  category_id integer [ref: > Category.id]
  primary key(course_id, category_id)
}

Table Module {
  id integer [primary key]
  module_order_no integer [note: 'An integer to rep the order of the module within the course']
  title varchar
  description text [note: 'About the module']
  content varchar
  course_id integer
  instructor_id integer
  created_at timestamp
  updated_at timestamp
}


Table Quiz {
  id integer [primary key]
  title varchar
  description text [note: 'A brief description or intructions for the quiz']
  time_limit integer
  passing_score integer
  course_id integer
  module_id integer
  attempts_allowed integer
  created_by_instructor_id integer
  created_at timestamp
  updated_at timestamp
}


Table Question {
  id integer [primary key]
  text varchar [note: 'the actual text of the quiz to which the question belongs']
  type varchar [note: 'type: multiple-choice, true/false, short-answer']
  options varchar[]   
  correct_answer varchar
  explanation text
  order integer
  quiz_id integer
  created_at timestamp
  updated_at timestamp
}


Ref: Instructor.user_id > User.id  

Ref: Course.instructor_id > Instructor.id

Ref: Module.course_id > Course.id

Ref: Module.instructor_id > Instructor.id

Ref: Quiz.course_id > Course.id

Ref: Quiz.module_id > Module.id

Ref: Quiz.created_by_instructor_id > Instructor.id

Ref: Question.quiz_id > Quiz.id

//Ref: user.id < instructor.user_id //one-to-many

